alias ls='ls --color=yes'
alias dir='dir --color=yes'
alias grep='grep --color=yes'
alias less='less -RM'
alias D='cd ~/Downloads'
alias d='cd ~/downloads'
alias v='nvim'
alias c='code'
alias g='git'
alias x='xmms2'
alias q='howdoi'
alias py='python3 -q'
alias py2='python2 -q'
alias rsc='rustc'                                                                                                       
alias rscd='rustdoc'
alias asc='asciinema'
alias gdb='gdb -q'
alias tmux='tmux -2'
alias startx='startx -- -dpi 102'
